# Dependencies
_ = require 'lodash'
util = require 'util'

# Const
BASE_URL = 'http://www.bijint.com/assets/pict'
AREAS =
  '奈良版': 'nara'
  '福岡版': 'fukuoka'
  '宮崎版': 'miyazaki'
  '岡山版': 'okayama'
  '茨城版': 'ibaraki'
  '山口版': 'yamaguchi'
  '新潟版': 'niigata'
  '宮城版': 'sendai'
  '京都版': 'kyoto'
  '神奈川版': 'kanagawa'
  '沖縄版': 'okinawa'
  '福井版': 'fukui'
  '徳島版': 'tokushima'
  '長野版': 'nagano'
  '東京版': 'tokyo'
  '栃木版': 'tochigi'
  '青森版': 'aomori'
  '鹿児島版': 'kagoshima'
  '愛知版': 'nagoya'
  '岩手版': 'iwate'
  '埼玉版': 'saitama'
  '広島版': 'hiroshima'
  '山梨版': 'yamanashi'
  '佐賀版': 'saga'
  '群馬版': 'gunma'
  '大阪版': 'osaka'
  '秋田版': 'akita'
  '香川版': 'kagawa'
  '長崎版': 'nagasaki'
  '北海道版': 'hokkaido'
  '静岡版': 'shizuoka'
  '石川版': 'kanazawa'
  '千葉版': 'chiba'
  '兵庫版': 'kobe'
  '鳥取版': 'tottori'
  '熊本版': 'kumamoto'
  'ジュニア時計': 'junior2'
  '早稲田スタイル時計': 'wasedastyle'
  'キッズ時計': 'kids'
  'マッチョ時計 for ラグビー': 'macho'
  '十勝キッズ時計': 'tokachi-kids02'
  'マスク美人': 'mask-bijin'
  'ぽちゃカワ時計': 'pochacawa'
  'パナホーム兵庫ファミリー時計': 'panahome-hyogo'
  'VIVI版': 'vivi'
  '美男時計': 'binan'
  '美魔女時計': 'bimajo'
  '美人時計全国版2012': '2012jp'
  'ヘアスタイル時計': 'hairstyle'
  '美人時計全国版2013': '2013jp'
  '美人時計全国版2011': '2011jp'
  'F・O・インターナショナル×キッズ時計': 'kids-fo'
  'Photo studio×キッズ時計': 'kids-photostudio'
  'BABYDOLL × I LOVE mama ×Primama × キッズ時計': 'kids-babydoll'
  'サーキット時計': 'cc'
  'SARA版': 'sara'
  '美男時計（鹿児島版）': 'binan-kagoshima'
  '美男時計 in 韓流ぴあ': 'binan_hanryupia'
  '美男時計（京都版）': 'binan-kyoto'
  'メガネ時計': 'megane'
  '花嫁時計': 'hanayome'
  'Thailand': 'thailand'
  'Taiwan': 'taiwan'
  'Hawaii': 'hawaii'
  'Jakarta': 'jakarta'

class BijinTokei
  @getAt: (time) ->
    area = _.sample AREAS
    util.format '%s/%s/pc/%s.jpg', BASE_URL, area, time

module.exports = BijinTokei